apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: admin
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - jsonPointers:
        - /data
      kind: Secret
  project: default
  source:
    path: adminapps/argocd
    repoURL: git@github.com:runitkr/infra.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
