apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: controller
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/controller.update-strategy: digest
    argocd-image-updater.argoproj.io/image-list: controller=ghcr.io/runitkr/controller:alpine
spec:
  destination:
    namespace: controller
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - jsonPointers:
        - /data
      kind: Secret
  project: default
  source:
    path: controller
    repoURL: git@github.com:runitkr/infra.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
