apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
spec:
  destination:
    namespace: ingress
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ingress-nginx
    helm:
      values: |-
        controller:
          kind: DaemonSet
          hostPort:
            enabled: true
            ports:
              http: 80
              https: 443
          service:
            type: ClusterIP
          config:
            allow-backend-server-header: 'true'
            use-forwarded-headers: 'true'
            proxy-request-buffering: 'off'
            proxy-body-size: '0'
            tcp-nodelay: 'on'
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: x
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - PruneLast=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
