apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: controller
  namespace: controller
spec:
  ingressClassName: nginx
  rules:
  - host: run.it.kr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: controller
            port:
              number: 8080
